# https://alacritty.org/config-alacritty.html

[general]
import = [
    "~/.config/alacritty/island_dark.toml",
    "~/.config/alacritty/keybindings.toml",
]

[window]
padding.x = 5
padding.y = 5

dimensions.columns = 190
dimensions.lines = 40
decorations = "Buttonless"
option_as_alt = "Both"

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 14.2

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style.shape = "Beam"
style.blinking = "Always"
