#:schema https://yazi-rs.github.io/schemas/theme.json

[mgr]
cwd = { fg = "#6F737A" }
border_style = { fg = "#313438" }

[tabs]
active = { bg = "#A1A3AB", fg = "#191A1C", bold = true }
inactive = { bg = "#5A5D63", fg = "#191A1C", bold = true }
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

[filetype]
rules = [
  { url = "*/", fg = "#DFE1E5" },
]

[indicator]
padding = { open = "█", close = "█" }
current = { bg = "#2E436E" }
parent = { bg = "#43454B" }
preview = { bg = "#43454B" }

[input]
border = { fg = "#313438", bg = "#191A1C" }
title = { fg = "#DFE1E5" }

[cmp]
border = { fg = "#313438", bg = "#191A1C" }
active = { bg = "#2E436E" }
icon_folder = ""

[tasks]
border = { fg = "#313438", bg = "#191A1C" }
title = { fg = "#DFE1E5" }

[which]
mask = { bg = "#2B2D30" }
cand = { fg = "#6F737A" }
desc = { fg = "#BCBEC4" }
separator_style = { fg = "#6F737A" }

[confirm]
title = { fg = "#DFE1E5" }
border = { fg = "#313438", bg = "#191A1C" }

[spot]
title = { fg = "#DFE1E5" }
border = { fg = "#313438", bg = "#191A1C" }
tbl_col = { fg = "#7A7E85" }
tbl_cell = { bg = "#2E436E" }

[notify]
title_info = { fg = "#3592C4" }
title_warn = { fg = "#F2C55C" }
title_error = { fg = "#FA6675" }
icon_info = ""
icon_warn = ""
icon_error = ""

[icon]
prepend_dirs = [
  { name = ".config", text = "󱂀" },
  { name = ".git", text = "󰊢" },
]
prepend_conds = [
  { if = "link", text = "" },
  { if = "dir", text = "" },
]
